### ISSUE TITLE
Encoding/Decoding bug on save

### ISSUE THREAD

**Issue by pvbernhard** [juzzlin/Heimer#71] opened 2019-12-30 09:15 UTC
I'm using Heimer 1.12.0 (but it says 1.11.0 on the title) on Windows 10.

There are two bugs related to saving and editing the file:

- Newlines are being added on top of newlines. Repro:
  1. Make a new file with a node with the text: `1<newline>2`, save it. PS: it seems the bug only happens if there is text before and after the newline.
  2. Open the file, click on the node but don't edit it or do anything.
  3. Close the file and save it. Heimer will say the file has been modified even though there should be no modification and will ask to save it.
  4. Open the file again. The text will be `1<newline><newline>2`.
  5. Repeat steps 2-4 (ii-iv), there will be a new newline every time you go through this process.
> Opening the file on a text editor after the step 3 (iii)  shows the newline as `&#xd;\r\n` instead of simply `\n`.

- Accents doesn't save. Repro:
  1. Make a new file with a node with the text `á`, save it.
  2. Open the file, the character will be `�`. Make some modification just to save the file again.
  3. Open the file again, now the character will be `?`.

>   Opening the file on a text editor after the step 1 (i) shows the character as `xE1`. Editing the file on a text editor to `á` makes Heimer show the character `á` correctly.

>   Likewise, opening the file on a text editor after the step 2 (ii) shows the character as `?`.

I hope this is helpful.

**Comment by juzzlin** [comment] 2019-12-31 19:59
Thanks for reporting! I'll investigate these issues.

**Comment by juzzlin** [comment] 2019-12-31 20:20
I updated the release with a rebuilt Windows installer and the version should be correct now. I don't know what had happened because it was correctly updated in the version control.

**Comment by juzzlin** [comment] 2019-12-31 20:27
I was able to reproduce the accent problem and it is somehow related to Windows as it seems to work correctly on Linux.

**Comment by juzzlin** [comment] 2019-12-31 20:51
That accent thing is now fixed in a6f071e8ab62d459bf02f7bdee5a84627aae8486.

**Comment by juzzlin** [comment] 2020-01-01 18:35
The newline issue also seems to be Windows-specific and doesn't happen on Linux.

**Comment by juzzlin** [comment] 2020-01-01 20:12
Newline bug fixed in 24f7c991aa2c776aded536444fb169b45f12d2b8.

**Comment by juzzlin** [comment] 2020-01-01 20:15
The undo thing you observed is currently by design. It was very hard to combine the built-in undo of the text field component and the global undo of Heimer so this current behavior is a compromise. I guess there's some hacks that could be done, but that's another issue then.

I'll create a new Heimer release soon.

**Closed by juzzlin** 2020-01-01 20:15 UTC
Labels: bug
