### ISSUE TITLE
Unpredictable crash on delete node via context menu (Ubuntu 18.04)

### ISSUE THREAD

**Issue by dluke** [juzzlin/Heimer#75] opened 2020-01-06 07:10 UTC
Heimer occasionally crashes for me when deleting a node.

Unfortunately I have not found a way to reliably reproduce this yet but it is important enough to report since it leads to immediate loss of work. 

It has always happened when deleting a node that I created unintentionally with an imprecise click, usually by unintentionally accessing the new-node-control of a node which is underneath and obscured by it's child (which I intend to drag). After some combination of imprecise clicking and dragging I end up with at least 1 more node than I intended and deleting one of these nodes causes the crash.

Apologies for what may be an unhelpful issue report. I will run in debug mode and attempt to elucidate the problem next time it occurs and perhaps others encountering the issue will understand it better than me.

**Comment by juzzlin** [comment] 2020-01-06 07:18
Thanks for reporting! I was able to reproduce at least one crash that happens if you quickly delete a node while the red dot animation is active.

**Comment by dluke** [comment] 2020-01-06 08:46
Red dot animation is quite slow so it's conceivable that was the one. I'll keep it in mind.

**Comment by juzzlin** [comment] 2020-01-06 09:08
It seems that I cannot consistently make it crash even when adjusting the animation to take several seconds to complete. It's very rare. I got one stack trace that lead deep inside Qt.

**Comment by juzzlin** [comment] 2020-01-06 10:18
I couldn't reproduce this anymore after f1f259457da5c9da2f1838e9a8cb88d3230f3044 so closing. I will create a new release later today.

**Closed by juzzlin** 2020-01-06 10:18 UTC
Labels: bug
