### ISSUE TITLE
Heimer not opening on Windows

### ISSUE THREAD

**Issue by IreneeThirion** [juzzlin/Heimer#135] opened 2021-01-24 10:40 UTC
I've dowloaded the latest version (2.2.2) of the software to run it on Windows but it's not starting.
I've used the .exe file and the program is installed but it doesn't open.
I've also tried the .zip file but the application doesn't open either...

I don't know if it's due to the configuration of my PC (a basic version of Windows 10) or to the program itself

**Comment by juzzlin** [comment] 2021-01-24 11:21
Windows shows an annoying warning the first time, but when that's accepted (More Info => Run anyway) the application starts at least on my Windows 10 normally.

![HeimerOnWindows10](https://user-images.githubusercontent.com/2587783/105628688-0ab11b00-5e47-11eb-9302-a572a0378c88.png)

**Comment by IreneeThirion** [comment] 2021-01-24 18:04
Hmm ok I've tried another time but it keeps failing to open :/
I think we don't get the same Windows "warning screen" when opening the application because the only warning screen that appears on my computer when using the .exe file is the same message you normally get when installing a software (so there is just a "yes" - "no" choice, no "More Info" => "Run anyway").
When using the application in the .zip file downloaded from Github, my computer just doesn't react (there is a blue circle around the mouse for a few seconds but then nothing happens)
I have another mindmapping software installed (Freeplane + Java to make it work) do you think it could interfere with Heimer ?
I can try try to record the screen to show you what happens in detail if it can be useful..

**Comment by juzzlin** [comment] 2021-01-24 18:15
I also downloaded the released zip. I don't think there can be any kind of interference with other software. You could try to start Heimer in the command prompt to see if it prints anything.

**Comment by juzzlin** [comment] 2021-01-24 18:17
Btw, has Heimer worked before on your computer or is this the first time you try to run it?

**Comment by IreneeThirion** [comment] 2021-01-24 18:35
> 
> 
> Btw, has Heimer worked before on your computer or is this the first time you try to run it?

No this is the first time I try to run it (I wanted to replace Freeplane which has a not-very-user-friendly UI)

**Comment by IreneeThirion** [comment] 2021-01-24 22:10
> 
> 
>You could try to start Heimer in the command prompt to see if it prints anything.

OK
I've tried but I'm not very used to the Windows command prompt
Anyway, the only result that I had when typing __start_ "C:\Program Files (x86)\Heimer"_ is a new command prompt window appearing.. is it a good sign ? Or did I made a mistake during the process ?

**Comment by juzzlin** [comment] 2021-01-25 11:58
You should go to the directory where `heimer.exe` is on your system and then just type `heimer`. You can change directory with the `cd` command.

**Comment by IreneeThirion** [comment] 2021-01-25 19:54
I've followed your instructions but unfortunately heimer keeps failing to open : nothing happens when using the command prompt on Windows (I've tried several times, with different methods)

**Comment by IreneeThirion** [comment] 2021-02-11 21:08
> I think we don't get the same Windows "warning screen" when opening the application because the only warning screen that appears on my computer when using the .exe file is the same message you normally get when installing a software (so there is just a "yes" - "no" choice, no "More Info" => "Run anyway").

Edit : I just got this type of warning screen when trying again to install heimer today. Anyway, I still can't open the application once it's installed :'(

**Comment by juzzlin** [comment] 2021-02-12 06:40
I'm sorry to hear that, but unfortunately I cannot help without seeing what the application possibly prints when started in command prompt.

**Comment by juzzlin** [comment] 2021-03-31 06:03
I'll close this for now, because more information is needed. I cannot reproduce the issue.

**Comment by mlovizio** [comment] 2021-05-08 13:53
I'm having the same issue here with W10, is weird because I have a really similar set up in my home pc and my office pc, both W10, and several programs in common, though in my home It doesn't run, just a few milliseconds of the circle next to the mouse and then nothing.

- I've tried both .exe and .zip
- running it as administrator
- running the compatibility mode
- running from cmd
- running from powershell

All with the same result: bitter failure...

I need a way to make windows show me again the warning sign of the unsigned that showed me the first time or at least how to generate some sort of crash log that I can share with you to debug this, I'm pretty sure that there is a simple thing that is preventing the app to run properly. 

Thanks in advanse juzzlin

**Comment by juzzlin** [comment] 2021-05-08 14:11
Does it print anything at all if started in command prompt with `heimer.exe --debug` ?

**Comment by juzzlin** [comment] 2021-05-08 14:56
Yes it would as the Windows version now uses a statically linked Qt build with MXE. Actually I don't believe there's necessarily anything wrong with the application code itself, but something weird related to this Qt arrangement perhaps. If it doesn't print anything then it fails very early for some reason (or is not even really started?). One thing would be to ensure that the failing and starting applications share exactly the same settings file.

**Comment by juzzlin** [comment] 2021-05-08 14:59
Should be easy to build on Windows. Download the Qt SDK (preferably newest 5.x), start Qt Creator, open the top-level CMakeLists.txt (or heimer.pro), build and run. In the case of CMakeLists.txt probably also CMake needs to be separately installed.

**Comment by juzzlin** [comment] 2021-05-08 15:04
Another thing to test: rename `heimer.exe` to something else e.g. `another.exe` and try starting then.

**Comment by mlovizio** [comment] 2021-05-08 15:06
> Another thing to test: rename `heimer.exe` to something else e.g. `another.exe` and try starting then.

Yes, I forgot to mention that, but I´ve tried renaming the .exe to other name but with no luck

**Comment by mlovizio** [comment] 2021-05-10 23:25
I think the problem is related to permissions in windows, here is what I've done:

1.  I've created a new user in windows
2. With the new user I've opened the .exe without any issue

I will dig into the details of my config to see what it is causing the problem, but maybe we should close the issue since it hasn't anything to do with the code itself.

**Comment by juzzlin** [comment] 2021-05-11 07:15
Great observation, thanks! I'll close this (again) :)

**Closed by juzzlin** 2021-05-11 07:15 UTC
Labels: bug

**Comment by eu2021** [comment] 2021-08-16 15:59
I also have this problem. The problem are profile names with special characters. Me and both users above have accents in the userfile name. The folders of the users above were:
C:\Users\René
C:\Users\Martín

That's why @mlovizio could make it work when he created another user.

I'm a computer programming noob, but I learned that profile names with special characters are a problem with this [Anki Addon](https://ankiweb.net/shared/info/579111794), that also have this problem, as they state: DOES NOT SUPPORT SPECIAL CHARACTERS IN PROFILE NAMES (#, $, ^, etc.).

Can it be fixed?

Thanks,

**Comment by juzzlin** [comment] 2021-08-16 17:40
Interesting and thanks for the information! I'm not sure if this can be easily fixed, but I can try something.
