### ISSUE TITLE
Edge text doesn't support Chinese fully

### ISSUE THREAD

**Issue by hongnod** [juzzlin/Heimer#218] opened 2022-09-07 02:55 UTC
Scene: Type Chinese text into an Edge. when mouse on the text, it will show, when mouse move out that text, text will disappear. and saved file lack of the typed Chinese.
[2022-09-07 10-54-12.zip](https://github.com/juzzlin/Heimer/files/9502351/2022-09-07.10-54-12.zip)

**Comment by juzzlin** [comment] 2022-09-07 06:09
Thanks for reporting!

I watched your video clip and that's definitely strange. Which Heimer version is that?

As I don't know how I could type Chinese on a Western keyboard I tried to copy-paste some Chinese text from Google Translate and I couldn't reproduce the issue that way with Heimer 3.6.0. 

Does this happen for you when copy-pasting Chinese text on the edge text input?

I need a way to reproduce this.

**Comment by hongnod** [comment] 2022-09-09 08:05
> Thanks for reporting!
> You are welcome
> I watched your video clip and that's definitely strange. Which Heimer version is that?
> v3.6.0
> As I don't know how I could type Chinese on a Western keyboard I tried to copy-paste some Chinese text from Google Translate and I couldn't reproduce the issue that way with Heimer 3.6.0.
>
> Does this happen for you when copy-pasting Chinese text on the edge text input?
>  Copy-pasted text works fine in my side too.
> I need a way to reproduce this.
IME text  

Very strange

**Comment by bommbo** [comment] 2022-09-18 09:44
same issue

**Comment by juzzlin** [comment] 2022-09-18 19:22
Some questions:

1) Windows or Linux version?

2) Does this work in older Heimer versions like 3.5.0?

3) Does the node text work properly?

**Comment by bommbo** [comment] 2022-09-19 00:36
linux version, just 3.6.0. Chinse character can't be saved.

**Comment by juzzlin** [comment] 2022-09-19 09:44
I managed to reproduce this on Ubuntu (input method Pinyin) and it seems that for some reason you need to press Enter to get the text "confirmed" after typing the desired text in Chinese.

**Comment by juzzlin** [comment] 2022-09-19 09:47
![ChineseTest](https://user-images.githubusercontent.com/2587783/190991848-68772029-172a-4ec4-b53c-bbf196fe40ba.png)

**Comment by bommbo** [comment] 2022-09-19 12:35
hhh, maybe next version will be fixed. 3.5.0 is ok.

**Comment by juzzlin** [comment] 2022-09-19 14:17
> hhh, maybe next version will be fixed. 3.5.0 is ok.

Really? That's weird, because I tested also with 3.5.0 and it had the same issue (also the node texts, not just edge texts).

**Comment by juzzlin** [comment] 2022-09-20 06:06
Actually it seems that you may also press the arrow right (probably also some other keys) to "commit" the entered text. Then it will be saved. To me this looks like a bug in Qt.

**Comment by bommbo** [comment] 2022-09-20 10:16
Actually I press space key to "commit" the text,so it's can't be saved. It's not a big issue.

**Comment by juzzlin** [comment] 2023-03-14 07:00
I'll close this one due to no activity.

**Closed by juzzlin** 2023-03-14 07:00 UTC
Labels: bug
