### ISSUE TITLE
Some problems about Heimer

### ISSUE THREAD

**Issue by TianshengSun** [juzzlin/Heimer#162] opened 2021-08-12 04:27 UTC
First of all, Heimer is really useful tool for me. I really like Heimer's ability to drag boxes.
But when i use Ctrl+z to redo some optations, Heimer will redo to much optations.  And some times, it can not save the file.  The notes are disappear,  when i save it , close it and open it again.

**Comment by juzzlin** [comment] 2021-08-13 07:26
Hi,

There seems to be some weird behavior if you create some nodes and then undo/redo/undo/redo.

**Comment by juzzlin** [comment] 2021-08-13 07:30
Added this: https://github.com/juzzlin/Heimer/issues/163

**Comment by juzzlin** [comment] 2021-08-13 07:31
If would need some more information of the saving problems. Can you reproduce that reliably by doing something?

**Comment by TianshengSun** [comment] 2021-08-14 14:47
Hi, 
I've tried to recreate this problem and I think I have known the reason for the storage problem. The storage problem occurs when I write Chinese to a block.

**Comment by SenlinOS** [comment] 2021-09-08 07:15
Reproduce, Chinese content cannot be saved!

Example text: 这是一个节点内容
(You can test it with this Chinese Text.)

**Comment by juzzlin** [comment] 2021-09-08 08:50
Works fine on Ubuntu 20.04. It produces this file and loads it successfully:

```
<?xml version='1.0' encoding='UTF-8'?>
<heimer-mind-map version="2.6.0">
 <color g="189" r="186" b="182"/>
 <edge-color g="0" r="0" b="0"/>
 <grid-color g="160" r="160" b="164"/>
 <edge-width>2000</edge-width>
 <text-size>11000</text-size>
 <corner-radius>5000</corner-radius>
 <graph>
  <node w="200000" x="0" y="0" h="75000" index="0">
   <text>这是一个节点内容</text>
   <color g="255" r="255" b="255"/>
   <text-color g="0" r="0" b="0"/>
  </node>
 </graph>
 <layout-optimizer min-edge-length="100000" aspect-ratio="1000"/>
</heimer-mind-map>
```

Haven't tested with Windows as I don't have Windows installed right now.

**Comment by SenlinOS** [comment] 2021-09-08 10:13
I use Xubuntu 20.04.

I have tested 10 times with other Chinese texts, and there were 2 times when the text was not saved completely and the text would be lost.
This seems to happen at random.

Thanks for your reply.

**Comment by juzzlin** [comment] 2021-12-14 12:43
I close this for now as I cannot reproduce this.

**Closed by juzzlin** 2021-12-14 12:43 UTC
Labels: bug

**Comment by SenlinOS** [comment] 2021-12-24 00:18
This Bug has been fixed after add Chinese translation and custom fonts.
Thank you :)
