### ISSUE TITLE
Decrease size of "About" dialog

### ISSUE THREAD

**Issue by Symbian9** [juzzlin/Heimer#195] opened 2021-12-26 15:54 UTC
- Version: `3.1.0`
- Platform: Linux (`AppImage`)

### Expected behaviour

About dialog should be as small as possible - so put small icon side-by-side with text: 

![Screenshot_2021-12-26_17-37-36](https://user-images.githubusercontent.com/13188580/147413459-b69600ee-152c-46a7-a5a4-aa6a4376988e.png)

### Actual behaviour

Actually "About" dialog is too large due to too large icon - as a result it does not fit even 720px in height (for creating video tutorials in 720p / 1280x720)

![Screenshot_2021-12-26_17-37-30](https://user-images.githubusercontent.com/13188580/147413488-c67538a6-749a-4436-a3ec-26eea75bd50b.png)

**Comment by juzzlin** [comment] 2021-12-26 16:52
Fixed in 32d3812297c1f1a8b57ecb72b3770a5a4b277131. Thanks for reporting!

**Closed by juzzlin** 2021-12-26 16:52 UTC
Labels: bug

**Comment by Symbian9** [comment] 2021-12-26 19:36
> Thanks for reporting!

JThanks for hotfix!

JFTR, Are there "nightly" AppImage builds available somewhere now?

**Comment by juzzlin** [comment] 2021-12-26 20:06
Unfortunately no, but meanwhile you can use this:

[Heimer-3.1.0-x86_64.AppImage.gz](https://github.com/juzzlin/Heimer/files/7777503/Heimer-3.1.0-x86_64.AppImage.gz)

**Comment by Symbian9** [comment] 2021-12-26 23:45
> Unfortunately no, but meanwhile you can use this (unzip and run):

Thanks! I just tried it and maybe one more change would be good to add — split `Heimer is licenced under GNU GPLv3. Copyright (c) 2018-2021 Jussi Lind.` sentences into 2 separate lines as next:

```
Heimer v3.1.0
Heimer is licenced under GNU GPLv3.
Copyright (c) 2018-2021 Jussi Lind.
Package type: AppImage
Project website: http://juzzlin.github.io/Heimer
Support Heimer via PayPal: https://paypal.me/juzzlin
```

This way about dialg also wold be a little bit more compact.

**Comment by Symbian9** [comment] 2021-12-26 23:46
> Unfortunately no, but meanwhile you can use this (unzip and run):

Thanks!

 I just tried it and maybe *one more change* would be good to add — split `Heimer is licenced under GNU GPLv3. Copyright (c) 2018-2021 Jussi Lind.` sentences into 2 separate lines as next:

```
Heimer v3.1.0
Heimer is licenced under GNU GPLv3.
Copyright (c) 2018-2021 Jussi Lind.
Package type: AppImage
Project website: http://juzzlin.github.io/Heimer
Support Heimer via PayPal: https://paypal.me/juzzlin
```

This way about dialg also wold be a little bit more compact also in width)

**Comment by juzzlin** [comment] 2021-12-27 07:29
The problem is that as the texts have translations in different languages the required width is not always the same. I need to check later today if the width could be made dynamic. Might not be easily possible due to the HTML content.

**Comment by Symbian9** [comment] 2021-12-27 20:26
@juzzlin, may you drop me AppImage built with latest commit, please?

**Comment by juzzlin** [comment] 2021-12-27 21:04
Here:

[Heimer-3.1.0-x86_64.AppImage.gz](https://github.com/juzzlin/Heimer/files/7781797/Heimer-3.1.0-x86_64.AppImage.gz)
